spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: postgres-prod
    password: Hajduhdodsfk2
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
